#!/bin/bash

git add $1

git update-index --chmod=+x $1

git add $1

echo "Enter commit message:"

read commitMessage
​
if [ -z $commitMessage ]
then
	commitMessage=$1
fi
​
git commit -m "$commitMessage"
git push