#!/bin/bash

git add .

git update-index --chmod=+x 100-times_table.c

git add .

git commit -m "The World looks like a multiplication-table, or a mathematical equation, which, turn it how you will, balances itself"

git push
