#!/bin/bash

git add .

git update-index --chmod=+x 100-print_comb3.c

git add .

git commit -m "Inventing is a combination of brains and materials. The more brains you use, the less material you need"

git push
