#!/bin/bash

git add .

git update-index --chmod=+x 2-print_alphabet.c

git add .

git commit -m "I sometimes suffer from insomnia. And when I can't fall asleep, I play what I call the alphabet game"

git push
