#!/bin/bash

git add .

git update-index --chmod=+x 101-print_comb4.c

git add .

git commit -m "The success combination in business is: Do what you do better... and: do more of what you do..."

git push
